In [1]:
!pip install numpy

In [3]:
import numpy as np

## create array using numpy

# 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# 2D array
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr = np.array([[1,2,3],[4,5,6]])

print("array:\n",arr)
print("shape:",arr.shape)
print("number of dimensions : ",arr.ndim)
print("size number of elements:",arr.size)
print("data type",arr.dtype)
print("item size in bytes:",arr.itemsize)


array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimensions :  2
size number of elements: 6
data type int64
item size in bytes: 8


In [15]:
## Numpy Vectorize operations

arr1 = np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element vise addition
print("Addition:",arr1+arr2)
print("Substraction",arr2-arr1)
print("Multiplication:",arr1*arr2)
print("Division:",arr2/arr1)

Addition: [11 22 33 44 55]
Substraction [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


In [18]:
## Universal function

arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
## Array slicing and indexing 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("arrya: \n",arr)

arrya: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [34]:
arr[1:,2:]


array([[ 7,  8],
       [11, 12]])

In [36]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [37]:
## Modify array elements 

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [38]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [40]:
### Statistical Concepts -- Normalization
## To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev
print(normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [44]:
data = np.array([1,2,3,4,5])

mean=np.mean(data)
print(mean)

median=np.median(data)
print(median)

std_dev=np.std(data)
print(std_dev)

variance=np.var(data)
print(std_dev)

3.0
3.0
1.4142135623730951
1.4142135623730951


In [50]:
## Logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5)&(data<8)]

array([6, 7])